name: 'build'

on:
   workflow_dispatch:
   schedule:
    - cron: "49 02 * * *"
   push:
    branches:
      - "*"

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Set env vars"
        run: |
          # TIPS!! Works as an export replacement, that handles GITHUB_ENV
          export_ga() {
            for _name in "${@}"
            do
              local _key="${_name%%=*}"
              local _value="${_name#*=}"
              [ "${_key}" == "${_name}" ] && _value="${!_name}"
              export $_key="${_value}"
              echo "${_key}=${_value}" >> "${GITHUB_ENV}"
            done
          }
          
          export_ga GITHUB_SHA_SHORT="$(git rev-parse --short HEAD)"

          export_ga GH_REGISTRY="ghcr.io"
          export_ga GH_USER="${{ github.actor }}"
          export_ga GH_OWNER="${{ github.repository_owner }}"
          export_ga REPO_NAME="${{ github.event.repository.name }}"
          
          export_ga IMAGE_NAME="${REPO_NAME#docker-*}"
          export_ga GH_IMAGE_NAME="${GH_REGISTRY}/${GH_OWNER}/${IMAGE_NAME}"

          export_ga BUILD_DATE="$(TZ=Europe/Paris date -Iseconds)"
          export_ga VERSION="$(curl -s https://api.github.com/repos/logseq/logseq/releases/latest | jq -r .tag_name | sed -e "s/^v//")"
          export_ga IMAGE_DESCRIPTION="Image for ${IMAGE_NAME} ( https://github.com/logseq/publish-spa )""

      - name: 'Login to github container registry'
        uses: "docker/login-action@v3"
        with:
          registry: "${{ env.GH_REGISTRY }}"
          username: "${{ env.GH_USER }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Build image builder"
        uses: docker/build-push-action@v6
        with:
          push: false
          no-cache: true
          tags: builder:latest

      - name: "Build image logseq-publish-spa ${{ env.GITHUB_SHA_SHORT }} (for version ${{ env.VERSION }})"
        uses: docker/build-push-action@v6
        with:
          push: true
          no-cache: true
          file: "Dockerfile-version"
          build-args: |
            GH_OWNER=${{ env.GH_OWNER }}
            GH_USER=${{ env.GH_USER }}
            GH_REGISTRY=${{ env.GH_REGISTRY }}
            IMAGE_NAME=${{ env.IMAGE_NAME }}
            REPO_NAME=${{ env.REPO_NAME }}
            DESCRIPTION=${{ env.IMAGE_DESCRIPTION }}
            VCS_REF=${{ env.GITHUB_SHA_SHORT }}
            BUILD_DATE=${{ env.BUILD_DATE }}
            VERSION=${{ env.VERSION }}
          tags: "${{ env.GH_IMAGE_NAME }}:${{env.GITHUB_SHA_SHORT}},${{ env.GH_IMAGE_NAME }}:${{ env.VERSION }},${{ env.GH_IMAGE_NAME }}:${{ env.VERSION }}-${{ env.GITHUB_SHA_SHORT }},${{ env.GH_IMAGE_NAME }}:latest"